name: financialratios
description: Financial Ratios by Ownership Financial

version: 1.0.0+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: 1.1.6+4
  path_provider: 1.3.0
  firebase_auth: 0.14.0+5
  sqflite_porter:
    git:
      url: git://github.com/tekartik/sqflite_more
      ref: dart2
      path: sqflite_porter
    version: ">=0.2.0"
  flutter_spinkit: 4.0.0
  provider: 3.1.0
  flutter_screenutil: 0.6.0
  flushbar: 1.9.0
  ulid: 1.0.2
  intl: 0.16.0
  catcher: 0.2.7
  keyboard_visibility: 0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_launcher_icons: "0.7.4"

#flutter_icons:
#android: "launcher_icon"
#ios: true
#image_path: "appicon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/json/
    - assets/cfg/
    - assets/images/
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
